site_name: Материалы для собеседований.
lsi: false
safe: true
source: https://github.com/devpilgrin/devpilgrin.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme:
    name: Cayman    
    locale: ru
    language: ru

